public with sharing class mc_MergeExternalServices_Definition {
    @AuraEnabled
    public String Id;
    @AuraEnabled
    public String Description;
    @AuraEnabled
    public String MasterLabel;
    @AuraEnabled
    public String NamedCredential;
    @AuraEnabled
    public String Schema;
    @AuraEnabled
    public String SchemaType;
    @AuraEnabled
    public String Status;
    @AuraEnabled
    public String SystemVersion;
}